import {
    AudioWaveform,
    Frame,
    PieChart,
    SquareTerminal,
    Building,
    Database,
    Server,
    LucideIcon,
    Settings,
    Users,
    FileText,
    ShoppingBag,
    Truck,
    Package,
    DollarSign,
    BarChart3,
    Activity,
    Shield,
    Eye,
    Menu,
    Home,
    User,
    Lock,
    Unlock,
    Bell,
    Search,
    Filter,
    RefreshCw,
    Edit,
    Trash2,
    Plus,
    ChevronDown,
    ChevronRight,
    LogOut,
    HelpCircle,
    CreditCard,
    Target,
    TrendingUp,
    Calendar,
    Clock,
    AlertCircle,
    CheckCircle,
    XCircle,
    Info,
    Map,
    Navigation,
    Zap,
    Cpu,
    HardDrive,
    Wifi,
    Battery,
    Cloud,
    Download,
    Upload,
    Share,
    Link,
    Mail,
    Phone,
    MessageSquare,
    Bookmark,
    Star,
    Heart,
    ThumbsUp,
    MessageCircle
} from "lucide-react";

// 图标名称到Lucide图标组件的映射
export const iconMap: Record<string, LucideIcon> = {
    // 原有图标
    'AudioWaveform': AudioWaveform,
    'Frame': Frame,
    'PieChart': PieChart,
    'SquareTerminal': SquareTerminal,
    'Building': Building,
    'Database': Database,
    'Server': Server,

    // 常用图标
    'Settings': Settings,
    'Users': Users,
    'User': User,
    'FileText': FileText,
    'ShoppingBag': ShoppingBag,
    'Truck': Truck,
    'Package': Package,
    'DollarSign': DollarSign,
    'BarChart3': BarChart3,
    'Activity': Activity,
    'Shield': Shield,
    'Eye': Eye,
    'Menu': Menu,
    'Home': Home,
    'Lock': Lock,
    'Unlock': Unlock,
    'Bell': Bell,
    'Search': Search,
    'Filter': Filter,
    'RefreshCw': RefreshCw,
    'Edit': Edit,
    'Trash2': Trash2,
    'Plus': Plus,
    'ChevronDown': ChevronDown,
    'ChevronRight': ChevronRight,
    'LogOut': LogOut,
    'HelpCircle': HelpCircle,
    'CreditCard': CreditCard,
    'Target': Target,
    'TrendingUp': TrendingUp,
    'Calendar': Calendar,
    'Clock': Clock,
    'AlertCircle': AlertCircle,
    'CheckCircle': CheckCircle,
    'XCircle': XCircle,
    'Info': Info,
    'Map': Map,
    'Navigation': Navigation,
    'Zap': Zap,
    'Cpu': Cpu,
    'HardDrive': HardDrive,
    'Wifi': Wifi,
    'Battery': Battery,
    'Cloud': Cloud,
    'Download': Download,
    'Upload': Upload,
    'Share': Share,
    'Link': Link,
    'Mail': Mail,
    'Phone': Phone,
    'MessageSquare': MessageSquare,
    'Bookmark': Bookmark,
    'Star': Star,
    'Heart': Heart,
    'ThumbsUp': ThumbsUp,
    'MessageCircle': MessageCircle,
};

/**
 * 根据图标名称获取对应的图标组件
 * @param iconName 图标名称
 * @returns Lucide图标组件，如果找不到则返回默认图标
 */
export function getIcon(iconName: string): LucideIcon {
    return iconMap[iconName] || SquareTerminal; // 默认图标
}

/**
 * 获取所有可用的图标名称列表
 * @returns 图标名称数组
 */
export function getAvailableIcons(): string[] {
    return Object.keys(iconMap);
}